name: Template - Collect Results

on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string

jobs:
  collect-results:
    runs-on: mi355x

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: '${{secret.GITHUB_TOKEN}}'
          fetch-depth: 0

      - name: Download JSON artifacts
        uses: actions/download-artifact@v5
        with:
          path: results/
          pattern: ${{ inputs.exp-name }}_*

      - name: Print summary
        run: python3 utils/summarize.py results/ ${{ inputs.exp-name }} >> $GITHUB_STEP_SUMMARY

      - name: Aggregate results
        run: python3 utils/collect_results.py results/ ${{ inputs.exp-name }}

      - name: Upload aggregated results
        uses: actions/upload-artifact@v4
        with:
          name: results_${{ inputs.exp-name }}
          path: agg_${{ inputs.exp-name }}.json
