name: Test - DeepSeek R1, SGLang on MI355

on:
  workflow_dispatch:
    inputs:
      run_1k1k:
        type: boolean
        required: true
      run_8k1k:
        type: boolean
        required: true
      run_1k8k:
        type: boolean
        required: true

      use_mi300x:
        type: boolean
        required: true
      use_mi325x:
        type: boolean
        required: true
      use_mi355x:
        type: boolean
        required: true

jobs:
  dsr1-1k1k:
    if: ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/dsr1-sgl-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-dsr1-1k1k-results:
    needs: dsr1-1k1k
    if: ${{ inputs.run_1k1k && always() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k1k'

  dsr1-8k1k:
    if: ${{ inputs.run_8k1k }}
    uses: ./.github/workflows/dsr1-sgl-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-dsr1-8k1k-results:
    needs: dsr1-8k1k
    if: ${{ inputs.run_8k1k && always() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_8k1k'

  dsr1-1k8k:
    if: ${{ inputs.run_1k8k }}
    uses: ./.github/workflows/dsr1-sgl-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k8k'
      isl: 1024
      osl: 8192
      max-model-len: 9216
      random-range-ratio: 0.8
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-dsr1-1k8k-results:
    needs: dsr1-1k8k
    if: ${{ inputs.run_1k8k && always() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k8k'
