name: Full Sweep Scheduler - 1k1k, B200

on:
  workflow_dispatch:

jobs:
  mega-run:
    uses: ./.github/workflows/full-sweep-tmpl.yml
    secrets: inherit
    with:
      run_1k1k: true
      run_8k1k: false
      run_1k8k: false
      use_h100: false
      use_h200: false
      use_b200: true 
      use_mi300x: false
      use_mi325x: false
      use_mi355x: false 
      use_gb200: false
